[workspace]
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[package]
name = "explore_game"
version = "0.1.0"
edition = "2021"
license = "ISC"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_asset_loader = "0.14.1"
bevy_mod_picking = "0.11"
bevy = { version = "0.9", features = ["dynamic", "wayland"] }
expl_hexgrid = { path = "crates/expl_hexgrid" }
expl_wfc = { path = "crates/expl_wfc" }
itertools = "0.10.5"
leafwing-input-manager = "0.8.0"
pathfinding = "4.2.1"
rand = "0.8.5"
smallvec = "1.6"
splines = { version = "4.2.0", features = ["glam"] }
futures-lite = "1.12.0"
clap = {version = "4.1.8", features = ["derive"] }
interpolation = "0.2.0"
hexasphere = "8.0.0"
glam = "0.23.0"
noisy_bevy = "0.2"
bevy_obj = "0.9.1"

[dev-dependencies]
rstest = { version = "0.16.0", default-features = false }
