[workspace]
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[package]
name = "explore_game"
version = "0.1.0"
edition = "2021"
license = "ISC"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_asset_loader = "0.17"
bevy_mod_picking = { version = "0.16", features = ["backend_egui"] }
bevy_obj = "0.11"
bevy = { version = "0.11", features = ["wayland", "dynamic_linking"] }
clap = { version = "4", features = ["derive"] }
expl_hexgrid = { path = "crates/expl_hexgrid", features = ["bevy-reflect"] }
expl_wfc = { path = "crates/expl_wfc" }
futures-lite = "2"
glam = "0.24"
interpolation = "0.3"
itertools = "0.12"
leafwing-input-manager = { version = "0.10", default-features = false, features = ["egui"] }
noisy_bevy = "0.5"
pathfinding = "4"
rand = "0.8"
smallvec = "1.11"
splines = { version = "4", features = ["glam"] }
bevy_mod_outline = "0.5"
bevy_sprite3d = "2.6"
bevy-inspector-egui = "0.19"
bevy_egui = "0.21"
bevy_mod_billboard = "0.4"
thiserror = "1.0.50"
moonshine-save = ">=0.3.2, <0.4"
platform-dirs = "0.3"
expl_databinding = { version = "0.1.0", path = "crates/expl_databinding" }
serde = "1.0"
expl_hexagon = { version = "0.1.0", path = "crates/expl_hexagon" }

[dev-dependencies]
approx = "0.5"
rstest = { version = "0.18.2", default-features = false }
