[workspace]
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[package]
name = "explore_game"
version = "0.1.0"
edition = "2021"
license = "ISC"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_asset_loader = "0.16"
bevy_mod_picking = { version = "0.12" }
bevy_obj = "0.10.1"
bevy = { version = "0.10", features = ["wayland", "dynamic_linking"] }
clap = {version = "4.3.0", features = ["derive"] }
expl_hexgrid = { path = "crates/expl_hexgrid" }
expl_wfc = { path = "crates/expl_wfc" }
futures-lite = "1.13.0"
glam = "0.24.0"
hexasphere = "8.0.0"
interpolation = "0.2.0"
itertools = "0.10.5"
leafwing-input-manager = "0.9"
noisy_bevy = "0.3"
pathfinding = "4.2.1"
rand = "0.8.5"
smallvec = "1.6"
splines = { git = "https://github.com/phaazon/splines.git", branch = "dependabot/cargo/master/glam-gte-0.10-and-lt-0.25", version = "4.2.0", features = ["glam"] }
bevy_mod_outline = "0.4.1"
bevy_sprite3d = "2.4.0"

[dev-dependencies]
rstest = { version = "0.17.0", default-features = false }
