[workspace]
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[package]
name = "explore_game"
version = "0.1.0"
edition = "2021"
license = "ISC"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_asset_loader = "0.17"
bevy_mod_picking = { version = "0.15", features = ["backend_egui"] }
bevy_obj = "0.11"
bevy = { version = "0.11", features = ["wayland", "dynamic_linking"] }
clap = {version = "4.4.2", features = ["derive"] }
expl_hexgrid = { path = "crates/expl_hexgrid" }
expl_wfc = { path = "crates/expl_wfc" }
futures-lite = "1.13.0"
glam = "0.24"
hexasphere = "9.1"
interpolation = "0.2.0"
itertools = "0.11.0"
leafwing-input-manager = { version = "0.10", default-features = false, features = ["egui"] }
noisy_bevy = "0.4"
pathfinding = "4.3.0"
rand = "0.8.5"
smallvec = "1.6"
splines = { git = "https://github.com/phaazon/splines.git", branch = "master", version = "4.2.0", features = ["glam"] }
bevy_mod_outline = "0.5"
bevy_sprite3d = "2.5"
bevy-inspector-egui = "0.19"
bevy_egui = "0.21"
bevy_mod_billboard = "0.4"
thiserror = "1.0.48"

[dev-dependencies]
rstest = { version = "0.18.2", default-features = false }
