[workspace]
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[package]
name = "explore_game"
version = "0.1.0"
edition = "2021"
license = "ISC"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.test.package."*"]
opt-level = 3

[dependencies]
bevy_asset_loader = "0.18"
bevy_egui = "0.23"
bevy-inspector-egui = "0.21"
bevy_mod_billboard = { git = "https://github.com/robtfm/bevy_mod_billboard/", version = "0.4.1", branch = "bevy12" }
bevy_mod_outline = "0.6"
bevy_mod_picking = { version = "0.17", features = ["backend_egui"] }
bevy_obj = "0.12"
bevy_sprite3d = "2.7"
bevy = { version = "0.12", features = ["wayland", "dynamic_linking", "file_watcher"] }
clap = { version = "4", features = ["derive"] }
expl_databinding = { version = "0.1.0", path = "crates/expl_databinding" }
expl_hexagon = { version = "0.1.0", path = "crates/expl_hexagon" }
expl_hexgrid = { path = "crates/expl_hexgrid", features = ["bevy-reflect"] }
expl_wfc = { path = "crates/expl_wfc" }
futures-lite = "2"
glam = "0.24"
interpolation = "0.3"
itertools = "0.12"
leafwing-input-manager = { version = "0.11.1", features = ["egui"] }
moonshine-save = "0.3.4"
noisy_bevy = "0.5"
pathfinding = "4"
platform-dirs = "0.3"
rand = "0.8"
serde = "1.0"
smallvec = "1.11"
splines = { version = "4", features = ["glam"] }
thiserror = "1.0.50"
expl_codex = { version = "0.1.0", path = "crates/expl_codex" }

[dev-dependencies]
approx = "0.5"
rstest = { version = "0.18.2", default-features = false }
