[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
skip = [
    "rustc-hash",
    "libloading",
    "core-foundation",
    "ttf-parser",
    "windows",
    "windows-core",
    "windows-result",
    "windows-sys",
    "toml_edit",
    "libredox",
    "ndk",
    "winnow",
    "syn",
    "ndk-sys",
    "hashbrown",
    "bitflags",
    "itertools",
    "downcast-rs",
    "getrandom",
    "linux-raw-sys",
    "miniz_oxide",
    "rustix",
    "thiserror",
    "thiserror-impl",
    "wasi",
    "core-graphics-types",
    "foldhash",
    "r-efi",
    "redox_syscall",
    "shlex",
    "toml_datetime",
    "windows-implement",
    "windows-interface",
    "windows-strings",
]
skip-tree = [
    { crate = "windows-targets", depth = 2 },
]
deny = [ ]
