[package]
name = "expl_hexgrid"
version = "0.1.0"
edition = "2021"
license = "ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
disjoint-hash-set = "1.0.0"
glam = ">=0.22, <0.24"
itertools = "0.11.0"
