[package]
name = "expl_databinding"
version = "0.1.0"
edition = "2021"
license = "ISC"

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_reflect = { workspace = true, features = ["smallvec"] }
smallvec.workspace = true
