[package]
name = "expl_wfc"
version = "0.1.0"
edition = "2021"
license = "ISC"

[lib]
bench = false

[dependencies]
bincode = "1.3.3"
data-encoding = "2.4.0"
expl_hexgrid = { path = "../expl_hexgrid" }
fixedbitset = "0.4.2"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
serde = { version = "1.0.164", features = ["derive"] }
thiserror = "1.0.47"

[dev-dependencies]
clap = { version = "4.3.21", features = ["derive"] }
criterion = "0.4.0"
more-asserts = "0.3.1"
pprof = { version = "0.12.0", features = ["flamegraph", "criterion"] }
rstest = { version = "0.17.0", default-features = false }
serde-jsonlines = "0.4.0"

[[bench]]
name = "generate"
harness = false
