name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Reveal permissions
      run: ls -l /usr/local
    - uses: keis/setup-mold@overwrite-dir
    - name: Reveal permissions
      run: ls -l /usr/local
