name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Blast some junk off the disk
      run: |
        df -h
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        sudo apt-get remove -y '^dotnet-.*' '^mongodb-.*' '^mysql-.*' '^llvm-.*' '^google-cloud-.*' azure-cli microsoft-edge-stable google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        df -h
        sudo rm -rf /usr/share/dotnet /usr/local/graalvm/ /usr/local/.ghcup/ /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/android /usr/local/lib/node_modules
        df -h
    - uses: actions/checkout@v4
    - name: Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - uses: Leafwing-Studios/cargo-cache@v1
    - name: Install dependencies
      run: |
        sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
        sudo apt-get clean
    - name: Test
      run: cargo test
    - name: Clippy
      uses: sksat/action-clippy@v0.2.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        filter_mode: nofilter
        reporter: github-pr-review
