name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Blast some junk off the disk
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet /usr/local/graalvm/ /usr/local/.ghcup/ /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/android /usr/local/lib/node_modules
        df -h
    - uses: actions/checkout@v4
    - name: Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - uses: rui314/setup-mold@v1
    - name: Install dependencies
      run: |
        sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev clang
    - uses: Leafwing-Studios/cargo-cache@v2
    - name: Test
      run: cargo test
  clippy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Blast some junk off the disk
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet /usr/local/graalvm/ /usr/local/.ghcup/ /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/android /usr/local/lib/node_modules
        df -h
    - uses: actions/checkout@v4
    - name: Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - uses: rui314/setup-mold@v1
    - name: Install dependencies
      run: |
        sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev clang
    - uses: Leafwing-Studios/cargo-cache@v2
    - name: Clippy
      uses: sksat/action-clippy@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        filter_mode: nofilter
        reporter: github-pr-review
